### ISSUE TITLE
i am getting following error even after allowing microphone access

### ISSUE THREAD

**Issue by anchalrani** [Kaljurand/dictate.js#14]
ERR: 3: Recorder undefined
ERR: 3: Recorder undefined
ERR: 3: Recorder undefined
msg: 2: Media stream created
msg: 1: Waiting for approval to access your microphone ...

**Comment by anchalrani** [comment]
the anove issue resolved by opening it in another browser.
but still getting 
Server error: 1: No speech

**Comment by Kaljurand** [comment]
Which browser/OS are you using?

**Comment by anchalrani** [comment]
i am using mozilla firefox, but i tried with google chrome and chromium browser too.

**Comment by Kaljurand** [comment]
Are you still experiencing this issue?

**Comment by 0x726574736F706D69** [comment]
Hi I am also getting this error.

On Ubuntu 22 and using Google Chrome, these are what I'm getting after ALLOWING microphone and trying to START recording:

ERR: 3: Recorder undefined
ERR: 3: Recorder undefined
ERR: 3: Recorder undefined
ERR: 3: Recorder undefined
msg: 2: Media stream created
msg: 1: Waiting for approval to access your microphone ...

Opening up console, I observe the following:

dictate.js:89 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

recorder.js:10 Uncaught (in promise) DOMException: Failed to construct 'Worker': Script at 'file:///home/ernest/Desktop/fyp-backup/ernest/dictate.js/lib/recorderWorker.js' cannot be accessed from origin 'null'.
    at new Recorder (file:///home/ernest/Desktop/fyp-backup/ernest/dictate.js/lib/recorder.js:10:18)
    at file:///home/ernest/Desktop/fyp-backup/ernest/dictate.js/lib/dictate.js:111:18

According to this stackoverflow [link](https://stackoverflow.com/questions/55026293/google-chrome-javascript-issue-in-getting-user-audio-the-audiocontext-was-not) , it seems that it is some google chrome policy.

If I run program on Ubuntu 22 Mozilla Firefox I do not encounter this error but it seems that when I start recording, all I get is this on the web UI:

msg: 9: [object Event]
msg: READY FOR SPEECH: 
msg: 13: Audio context resumed

On MacOSX, whether I use firefox or chrome, it does not happen. Please help.
